### ISSUE TITLE
Split out Drupal install step and module install

### ISSUE THREAD

**Issue by nerdstein** [LionsAd/drupal_ti#39]
Currently, "before_script" performs the following actions:

1. Drupal core dl
2. Drupal site install
3. (Github) Module install

Most 8.x module dependencies do not have releases on drupal.org yet. As such, step 3 fails because module dependencies are not found. There have also been known Drush issues with downloading and discovering dependencies (which is out of your hands).

I would develop `drupal-ti before_script` to call `drupal-ti site-install` (steps 1 and 2 noted above) and `drupal-ti module_install` (steps 3 above).  

This enables a user to call `drupal-ti before_script` if they have no issues with dependencies, or they can call `drupal-ti site-install`, their own logic, and then `drupal-ti module_install` if they need more customization.

**Comment by cthos** [comment]
So, I think breaking the `before_script` step out isn't necessarily the best approach to solving your issue, but I'd like to suggest an alternative.

First, the reasoning behind my statement. `drupal-ti before_script` is designed to just iterate over any runners that are enabled and then call the corresponding `before_script.sh` file (assuming one exists). Breaking that out into 2 different steps would break the concept of "one file per travis build step".

What it sounds like you're really needing is the ability to customize an interstitial step between the install and the check to ensure the modules exist.

My suggestion would be to do the following:

* Create an environment variable called `DRUPAL_TI_AFTER_DRUPAL_INSTALL` (or something). Which points to a shell script.
* If this script exists, drupal-ti will `source` that file, so that any interstitial steps can be called.
* Modify [drupal.sh](https://github.com/LionsAd/drupal_ti/blob/master/functions/drupal.sh)'s `drupal_ti_ensure_drupal` to source that script after it calls `drupal_ti_install_drupal`.

It'd operate in a manner similar to `DRUPAL_TI_SCRIPT_DIR_BEFORE="./drupal_ti/before"`, and wouldn't require breaking the before_script steps into multiple actions (which would be a bit tricky).

**Comment by damontgomery** [comment]
#15 resolved this issue (or at least introduced a work-around) and I updated the docs in #45. I think we can mark this resolved. I agree that a more friendly way to do this would be nice, but this seems to be the pattern people are currently following and it seems to get the job done.

**Comment by aquicthos** [comment]
I don't feel particularly strongly about it, so I'm fine with closing the issue. :+1:

**Comment by LionsAd** [comment]
Thanks for the discussion, closing for now.
